# Generated by Django 4.2.7 on 2023-11-22 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='fullname',
        ),
        migrations.AddField(
            model_name='registration',
            name='age',
            field=models.TextField(default='0', max_length=100),
        ),
        migrations.AddField(
            model_name='registration',
            name='firstname',
            field=models.TextField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='registration',
            name='gender',
            field=models.TextField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='registration',
            name='lastname',
            field=models.TextField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='registration',
            name='moiddlename',
            field=models.TextField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='registration',
            name='client_id',
            field=models.TextField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='registration',
            name='mobile',
            field=models.TextField(default='0xxx', max_length=15),
        ),
    ]
